name: "Informous"
author: "Jatyn Stacy"
version: ${version}
api-version: "1.19"
main: "com.knockturnmc.informous.Informous"
load: STARTUP

loader: com.knockturnmc.informous.InformousPluginLoader
has-open-classloader: true

commands:
  relay-test:
    description: "Throws a runtime exception to test the exception relay."