name: "Informous"
author: "Jatyn Stacy"
version: ${version}
api-version: "1.19"
main: "com.knockturnmc.informous.Informous"
load: STARTUP

libraries:
  - ${kotlinCoroutines}
  - ${kotlinReflect}

commands:
  relay-test:
    description: "Throws a runtime exception to test the exception relay."